# fly.toml app configuration file generated for server-email on 2025-11-29T12:55:40+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-email'
primary_region = 'fra'

[build]

[[services]]
    internal_port = 8080
    protocol = "tcp"
    auto_stop_machines = "suspend"
    auto_start_machines = true
    min_machines_running = 0

[[vm]]
    size = 'shared-cpu-1x'
    processes = ['app']